name: UHC
main: nao20010128nao\UHC
version: 1.0.0
api: [1.0.0]
load: STARTUP
author: nao20010128nao
description: DESC
website: https://github.com/nao20010128nao
permissions:
 uhc.*:
  children:
   uhc.all:
    description: ""
     children:
      uhc.players:
       description: ""
      uhc.admin:
       description: ""
       default: op
